// Package contract tests RFC 6762 compliance for mDNS query/response behavior.
package contract

import (
	"context"
	"fmt"
	"net"
	"testing"
	"time"

	"github.com/joshuafuller/beacon/internal/message"
	"github.com/joshuafuller/beacon/internal/protocol"
	"github.com/joshuafuller/beacon/internal/transport"
	"github.com/joshuafuller/beacon/querier"
)

// TestQuery_RFC6762_QueryHeaderFields validates that Query() generates
// query messages with correct header fields per RFC 6762 §18 (FR-020).
//
// RFC 6762 Requirements:
//
//	§18.2: QR bit MUST be zero in query messages
//	§18.3: OPCODE MUST be zero (standard query)
//	§18.4: AA bit MUST be zero in query messages
//	§18.5: TC bit clear means no additional Known Answers
//	§18.6: RD bit SHOULD be zero (M1 enforces MUST for simplicity)
//
// FR-020: System MUST set DNS header fields per RFC 6762 §18
//
// NOTE: This test validates the message format by inspecting the wire format
// generated by the internal builder (indirectly through Query behavior)
func TestQuery_RFC6762_QueryHeaderFields(t *testing.T) {
	q, err := querier.New()
	if err != nil {
		t.Fatalf("New() failed: %v", err)
	}
	defer func() { _ = q.Close() }()

	// Create a custom querier that captures outgoing messages
	// For M1, we validate this through the builder tests
	// This test validates the integration: Query() → BuildQuery() → correct headers

	ctx, cancel := context.WithTimeout(context.Background(), 100*time.Millisecond)
	defer cancel()

	// Query should succeed (even with timeout)
	_, err = q.Query(ctx, "test.local", querier.RecordTypeA)
	if err != nil && err != context.DeadlineExceeded {
		t.Logf("Query() returned error: %v (acceptable in isolated test)", err)
	}

	// Validation: The fact that Query() completes without panic validates
	// that the internal BuildQuery() produces valid messages per RFC 6762 §18
	// Detailed header validation is in internal/message/builder_test.go
	t.Logf("Query() executed successfully - header validation in builder_test.go")
}

// TestQuery_RFC6762_ResponseValidation validates that Query() only accepts
// valid response messages per RFC 6762 (FR-021, FR-022).
//
// RFC 6762 Requirements:
//
//	§18.2: Response messages MUST have QR bit set to 1
//	§18.11: mDNS responders MUST ignore messages with non-zero RCODE
//
// FR-021: System MUST verify QR bit is set in response messages
// FR-022: System MUST validate RCODE is 0 per RFC 6762 §18.11
//
// NOTE: This test validates response filtering - malformed responses should be ignored
func TestQuery_RFC6762_ResponseValidation(t *testing.T) {
	q, err := querier.New()
	if err != nil {
		t.Fatalf("New() failed: %v", err)
	}
	defer func() { _ = q.Close() }()

	ctx, cancel := context.WithTimeout(context.Background(), 500*time.Millisecond)
	defer cancel()

	// Query for a common mDNS service discovery query
	// Any responses received should have been validated per FR-021, FR-022
	response, err := q.Query(ctx, "_services._dns-sd._udp.local", querier.RecordTypePTR)
	if err != nil {
		t.Logf("Query() returned error: %v (acceptable in isolated test)", err)
		return
	}

	// If we got responses, they were already validated per FR-021, FR-022
	if response != nil && len(response.Records) > 0 {
		t.Logf("Query() received %d valid responses (passed RFC validation per FR-021, FR-022)", len(response.Records))

		// Additional validation: Verify no record has invalid flags
		// This would indicate validation bypassed
		for i, record := range response.Records {
			if record.Name == "" {
				t.Errorf("Record[%d] has empty name (invalid response accepted)", i)
			}
			if record.TTL == 0 {
				t.Logf("Record[%d] has TTL=0 (valid for cache flush per RFC 6762)", i)
			}
		}
	} else {
		t.Logf("Query() received no responses (timeout - acceptable)")
	}
}

// TestQuery_RFC6762_IgnoreMalformedResponses validates that Query() discards
// malformed packets per FR-011, FR-016.
//
// FR-011: System MUST validate response message format and discard malformed packets
// FR-016: System MUST continue collecting responses after discarding malformed packets
//
// NOTE: This test validates resilience - one bad packet shouldn't break query
func TestQuery_RFC6762_IgnoreMalformedResponses(t *testing.T) {
	q, err := querier.New()
	if err != nil {
		t.Fatalf("New() failed: %v", err)
	}
	defer func() { _ = q.Close() }()

	ctx, cancel := context.WithTimeout(context.Background(), 200*time.Millisecond)
	defer cancel()

	// Query a common name - if malformed packets exist on network, they should be ignored
	response, err := q.Query(ctx, "test.local", querier.RecordTypeA)

	// Query should complete without panic (even if malformed packets received)
	if err != nil && err != context.DeadlineExceeded {
		t.Logf("Query() returned error: %v (acceptable)", err)
		return
	}

	if response == nil {
		t.Logf("Query() received no responses (timeout or all malformed)")
		return
	}

	// If we got responses, validate they're well-formed
	for i, record := range response.Records {
		if record.Name == "" {
			t.Errorf("Record[%d] has empty name (malformed response not filtered per FR-011)", i)
		}

		// Validate Type matches query
		if record.Type != querier.RecordTypeA {
			t.Logf("Record[%d] has type %v (expected A) - possibly from cache or additional section", i, record.Type)
		}
	}

	t.Logf("Query() completed with %d valid records (malformed responses filtered per FR-011, FR-016)", len(response.Records))
}

// TestQuery_RFC1035_NameCompression validates that Query() handles compressed
// names in responses per RFC 1035 §4.1.4 (FR-012).
//
// RFC 1035 §4.1.4: DNS message compression using pointers
//
// FR-012: System MUST decompress DNS names per RFC 1035 §4.1.4
//
// NOTE: This test validates that responses with compressed names are parsed correctly
func TestQuery_RFC1035_NameCompression(t *testing.T) {
	q, err := querier.New()
	if err != nil {
		t.Fatalf("New() failed: %v", err)
	}
	defer func() { _ = q.Close() }()

	ctx, cancel := context.WithTimeout(context.Background(), 300*time.Millisecond)
	defer cancel()

	// Query for PTR record (service discovery) - these typically use compression
	response, err := q.Query(ctx, "_http._tcp.local", querier.RecordTypePTR)
	if err != nil {
		t.Logf("Query() returned error: %v (acceptable in isolated test)", err)
		return
	}

	if response == nil || len(response.Records) == 0 {
		t.Logf("Query() received no PTR responses (timeout - acceptable)")
		return
	}

	// Validate that names were decompressed properly
	for i, record := range response.Records {
		if record.Name == "" {
			t.Errorf("Record[%d] has empty name (compression failed per FR-012)", i)
		}

		// PTR records should have valid target names
		if record.Type == querier.RecordTypePTR {
			// Data should be a string (decompressed PTR target)
			if ptrTarget, ok := record.Data.(string); ok {
				if ptrTarget == "" {
					t.Errorf("Record[%d] PTR target is empty (compression failed per FR-012)", i)
				}
				t.Logf("Record[%d] PTR: %s → %s (decompressed per FR-012)", i, record.Name, ptrTarget)
			}
		}
	}

	t.Logf("Query() successfully decompressed %d PTR records per FR-012", len(response.Records))
}

// TestQuery_RFC6762_MultipleResponses validates that Query() aggregates
// multiple responses per FR-007, FR-008.
//
// FR-007: System MUST deduplicate identical responses from multiple responders
// FR-008: System MUST aggregate responses received within timeout window
//
// Drives this via a mock transport queued with synthetic PTR answers
// (simulating multiple distinct responders answering the DNS-SD meta-query,
// per RFC 6763 §9, plus one exact duplicate) rather than querying the real
// LAN. Real service discovery traffic made this test both non-deterministic
// (record count depends on what's on the network) and silently wrong: the
// old duplicate check keyed only on Name+Type, but every answer to this
// meta-query shares the same Name ("_services._dns-sd._udp.local") and Type
// (PTR) and differs only in RDATA - so it flagged every distinct real
// service type as a "duplicate" of the first.
func TestQuery_RFC6762_MultipleResponses(t *testing.T) {
	mock := transport.NewMockTransport()
	q, err := querier.New(querier.WithTransport(mock))
	if err != nil {
		t.Fatalf("New() failed: %v", err)
	}
	defer func() { _ = q.Close() }()

	serviceTypes := []string{"_http._tcp.local", "_ipp._tcp.local", "_ssh._tcp.local"}
	srcAddr := &net.UDPAddr{IP: net.ParseIP("192.168.1.10"), Port: 5353}
	for i, svcType := range serviceTypes {
		target, err := message.EncodeName(svcType)
		if err != nil {
			t.Fatalf("EncodeName(%q) failed: %v", svcType, err)
		}
		packet, err := message.BuildResponse([]*message.ResourceRecord{{
			Name:  "_services._dns-sd._udp.local",
			Type:  protocol.RecordTypePTR,
			Class: protocol.ClassIN,
			TTL:   120,
			Data:  target,
		}})
		if err != nil {
			t.Fatalf("BuildResponse(%q) failed: %v", svcType, err)
		}
		mock.QueueReceive(packet, srcAddr, 0)
		if i == 0 {
			// A second responder answering with the exact same record - FR-007.
			mock.QueueReceive(packet, srcAddr, 0)
		}
	}

	ctx, cancel := context.WithTimeout(context.Background(), 300*time.Millisecond)
	defer cancel()

	response, err := q.Query(ctx, "_services._dns-sd._udp.local", querier.RecordTypePTR)
	if err != nil {
		t.Fatalf("Query() error = %v", err)
	}

	if len(response.Records) != len(serviceTypes) {
		t.Fatalf("Query() aggregated %d records, want %d (duplicate answer must be deduplicated per FR-007)",
			len(response.Records), len(serviceTypes))
	}
	t.Logf("Query() aggregated %d distinct responses per FR-008", len(response.Records))

	seen := make(map[string]bool)
	for _, record := range response.Records {
		key := fmt.Sprintf("%s|%d|%v", record.Name, record.Type, record.Data)
		if seen[key] {
			t.Errorf("Query() returned duplicate record %q (deduplication failed per FR-007)", key)
		}
		seen[key] = true
	}
}
