#!/bin/bash
# RFC Compliance Checker - Verifies implementation against RFC requirements
#
# Usage:
#   ./scripts/check-rfc-compliance.sh              # Full report
#   ./scripts/check-rfc-compliance.sh --strict     # Exit 1 if P0 gaps found
#   ./scripts/check-rfc-compliance.sh --summary    # Summary only
#
# Requires:
#   - RFC_REQUIREMENTS_COMPLETE.md (generated by extract_rfc_requirements.py)

set -euo pipefail

BEACON_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REQUIREMENTS_FILE="${BEACON_ROOT}/RFC_REQUIREMENTS_COMPLETE.md"
STRICT_MODE=false
SUMMARY_ONLY=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --strict)
            STRICT_MODE=true
            shift
            ;;
        --summary)
            SUMMARY_ONLY=true
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "═══════════════════════════════════════════════════════════"
echo "  RFC 6762/6763 Compliance Checker"
echo "═══════════════════════════════════════════════════════════"
echo

if [[ ! -f "$REQUIREMENTS_FILE" ]]; then
    echo "${RED}ERROR: Requirements file not found: $REQUIREMENTS_FILE${NC}"
    echo "Run: python3 extract_rfc_requirements.py"
    exit 1
fi

# Extract statistics from requirements file
# Parse from Summary section (lines 7-29 typically)
total_reqs=$(grep "^\*\*Total Requirements\*\*: " "$REQUIREMENTS_FILE" | sed 's/[^0-9]//g')
must_reqs=$(grep "^\- \*\*MUST\*\*: " "$REQUIREMENTS_FILE" | head -1 | awk '{print $3}')
should_reqs=$(grep "^\- \*\*SHOULD\*\*: " "$REQUIREMENTS_FILE" | head -1 | awk '{print $3}')
may_reqs=$(grep "^\- \*\*MAY\*\*: " "$REQUIREMENTS_FILE" | head -1 | awk '{print $3}')

# Implementation status from "Implementation Status" section
# Format: "- ✅ **Complete**: 183 (97%)"
# Fields: $1=-, $2=✅, $3=**Complete**:, $4=183
implemented=$(grep "\*\*Complete\*\*: " "$REQUIREMENTS_FILE" | head -1 | awk '{print $4}')
partial=$(grep "\*\*Partial\*\*: " "$REQUIREMENTS_FILE" | head -1 | awk '{print $4}')
missing=$(grep "\*\*Missing\*\*: " "$REQUIREMENTS_FILE" | head -1 | awk '{print $4}')

# P0 gaps from "P0 (MUST) Gap Analysis" section
# Format: "- ❌ Missing: 0"
p0_gaps=$(grep "^\- .*Missing: " "$REQUIREMENTS_FILE" | grep -v "Total P0" | head -1 | awk '{print $4}')

# Set defaults if parsing failed
total_reqs=${total_reqs:-0}
must_reqs=${must_reqs:-0}
should_reqs=${should_reqs:-0}
may_reqs=${may_reqs:-0}
implemented=${implemented:-0}
partial=${partial:-0}
missing=${missing:-0}
p0_gaps=${p0_gaps:-0}

# Calculate compliance percentage
if [[ $total_reqs -gt 0 ]]; then
    compliance_pct=$(awk "BEGIN {printf \"%.1f\", ($implemented + $partial * 0.5) / $total_reqs * 100}")
else
    compliance_pct=0.0
fi

# Print summary
echo "📊 Requirements Summary"
echo "───────────────────────────────────────────────────────────"
echo "Total Requirements:     $total_reqs"
echo "  - MUST (P0):          $must_reqs"
echo "  - SHOULD (P1):        $should_reqs"
echo "  - MAY (P2):           $may_reqs"
echo

echo "📈 Implementation Status"
echo "───────────────────────────────────────────────────────────"
echo -e "  ${GREEN}✅ Implemented:${NC}        $implemented"
echo -e "  ${YELLOW}⚠️  Partial:${NC}            $partial"
echo -e "  ${RED}❌ Missing:${NC}             $missing"
echo

echo "🎯 Compliance Metrics"
echo "───────────────────────────────────────────────────────────"
echo -e "Overall Compliance:     ${BLUE}${compliance_pct}%${NC}"
echo -e "P0 Gaps (MUST):         ${RED}${p0_gaps}${NC}"
echo

# Compliance gate
if [[ "$compliance_pct" == 100* ]]; then
    echo -e "${GREEN}✅ STATUS: FULLY COMPLIANT${NC}"
    exit_code=0
elif [[ $p0_gaps -eq 0 ]]; then
    echo -e "${GREEN}✅ STATUS: P0 COMPLIANT (all MUST requirements met)${NC}"
    exit_code=0
else
    echo -e "${RED}❌ STATUS: NON-COMPLIANT ($p0_gaps P0 gaps remaining)${NC}"
    exit_code=1
fi

echo

# Detailed report (unless --summary)
if [[ "$SUMMARY_ONLY" != true ]]; then
    echo "📋 Detailed Gap Analysis"
    echo "───────────────────────────────────────────────────────────"

    # Extract and display P0 gaps
    if [[ $p0_gaps -gt 0 ]]; then
        echo -e "${RED}P0 GAPS (MUST requirements):${NC}"
        echo

        # Parse requirements file for P0 gaps
        # This is a simplified version - would need more robust parsing
        awk '
            /^#### RFC676/ {
                capturing = 1
                req_id = $0
                next
            }
            capturing && /Type.*: MUST/ {
                is_must = 1
            }
            capturing && /Status.*: ❌/ && is_must {
                print "  " req_id
            }
            capturing && /^#### / {
                capturing = 0
                is_must = 0
            }
        ' "$REQUIREMENTS_FILE" | sed 's/^####/  /'
        echo
    fi

    # Extract SHOULD gaps
    p1_gaps=$(grep -B5 "Status.*: ❌" "$REQUIREMENTS_FILE" | grep "Priority.*: P1" | wc -l || echo 0)
    if [[ $p1_gaps -gt 0 ]]; then
        echo -e "${YELLOW}P1 GAPS (SHOULD requirements): $p1_gaps${NC}"
        echo "(Run with full output to see details)"
        echo
    fi
fi

# Strict mode exit
if [[ "$STRICT_MODE" == true ]] && [[ $p0_gaps -gt 0 ]]; then
    echo -e "${RED}STRICT MODE: Failing due to $p0_gaps P0 gaps${NC}"
    exit 1
fi

exit $exit_code
